[package]
name = "nevealdj_sound_engine"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
cpal = "0.16.0"
hound = "3.5.1"
napi = { version = "3.7.0", features = ["napi4"] }
napi-derive = "3.4.0"
